Features/advantages
artem-bilodid/parcel-project-template pull request #23
Opened 2021-06-06 12:14 UTC by ttuluk

2021-06-06 15:58 UTC, MyroniukIS commented on src/sass/base/_base.scss
> -  outline: 1px solid palevioletred;
Може б нехай кожен собі сам ставив аутлайн? Я от, наприклад без нього працюю... Давайте обговоримо це на Стендапі!
А взагалі - красавчик! Я за ці базові стилі якраз сьогодні подумала, що чому це їх немає =)

2021-06-06 15:59 UTC, MyroniukIS commented on src/sass/layout/_advantages.scss
> +    @media screen and (min-width: 1200px) {
хіба в нас в ТЗ точка перелому не 1280??

2021-06-06 16:01 UTC, MyroniukIS commented on src/sass/layout/_advantages.scss
>      font-family: DM Sans;
у нас є змінні для фонтів $fontAccent - це Titan One, а DM Sans загально застосовується

2021-06-06 16:03 UTC, MyroniukIS requested changes, later dismissed

2021-06-06 16:03 UTC, MyroniukIS commented on src/sass/layout/_advantages.scss
>      color: #000000;
Танюха, ти ж нам змінні зробила! ;)

2021-06-06 16:48 UTC, ttuluk commented on src/sass/base/_base.scss
> -  outline: 1px solid palevioletred;
Так outline  я и делала сама себе, красным он просто удален

2021-06-06 16:49 UTC, ttuluk commented on src/sass/layout/_advantages.scss
>      color: #000000;
я не ставила font-size  в переменные

2021-06-06 16:49 UTC, ttuluk commented on src/sass/layout/_advantages.scss
>      font-family: DM Sans;
ок, удалю

2021-06-06 18:31 UTC, artem-bilodid requested changes

2021-06-06 18:31 UTC, artem-bilodid commented on src/sass/layout/_advantages.scss
> +}
эти картинки и стили лишние, у картинок на десктопе такой же размер

2021-06-06 18:31 UTC, artem-bilodid commented on src/partials/advantages.html
> +    <h2 class="visually-hidden">Advantages</h2>
вынести .container отдельно в .advantages__container
ограничить ширину контейнера на точках перелома 480, 768, 1280

2021-06-06 18:31 UTC, artem-bilodid commented on src/sass/layout/_advantages.scss
> +    background-color: var(--color-prime);
неправильный цвет фона

2021-06-06 18:31 UTC, artem-bilodid commented on src/sass/layout/_advantages.scss
>      color: #000000;
тут речь про цвет)

2021-06-06 18:31 UTC, artem-bilodid commented on src/sass/layout/_advantages.scss
> +    font-style: 400;
удалить, такого css  правила не существует

2021-06-06 18:31 UTC, artem-bilodid commented on src/sass/layout/_advantages.scss
> +.list {
класс убрать, перенести стили в .advantages__list

2021-06-06 18:31 UTC, artem-bilodid commented on src/partials/advantages.html
> +    <ul class="advantages__list list">
класс убрать, перенести стили в .advantages__list

2021-06-06 18:31 UTC, artem-bilodid commented on src/sass/layout/_advantages.scss
> +    font-family: Titan One;
заменить на $fontAccent

2021-06-06 18:31 UTC, artem-bilodid commented on src/sass/layout/_advantages.scss
> +    }
эти картинки и стили лишние, у картинок на десктопе такой же размер

2021-06-06 18:31 UTC, artem-bilodid commented on src/sass/layout/_advantages.scss
> +    }
сделать просто advantages-icon и вынести наружу из медиа запросов

2021-06-06 18:31 UTC, artem-bilodid commented on src/sass/layout/_advantages.scss
> +  .advantages__text {
добавить margin-top (расстояние до counter) для всех разрешений

2021-06-06 18:31 UTC, artem-bilodid commented on src/sass/layout/_advantages.scss
> +    margin-left: 60px;
margin-left: 30px;

2021-06-06 18:31 UTC, artem-bilodid commented on src/sass/layout/_advantages.scss
> +    font-style: 400;
font-style: 400; - такого сss правила нету

2021-06-06 19:35 UTC, MyroniukIS commented on src/sass/base/_base.scss
> -  outline: 1px solid palevioletred;
А, сорі, недогледіла

2021-06-06 19:35 UTC, MyroniukIS commented on src/sass/layout/_advantages.scss
>      color: #000000;
Да

2021-06-06 19:37 UTC, MyroniukIS commented on src/sass/layout/_advantages.scss
> +    font-style: 400;
Ти мабуть з font-weight переплутала

2021-06-07 20:32 UTC, artem-bilodid approved these changes

2021-06-07 20:32 UTC, merged