Feature/contacts
artem-bilodid/parcel-project-template pull request #25
Opened 2021-06-06 16:14 UTC by osipm

готова секція contacts

2021-06-06 16:41 UTC, artem-bilodid commented on src/icons/sprite.svg
> +</symbol></defs></svg>
тут добавился только перенос строки?
если иконка не добавлялась - лучше отменить это изменение

2021-06-06 16:44 UTC, artem-bilodid commented on src/icons/icon.svg
> +<svg aria-hidden="true" style="position: absolute; width: 0; height: 0; overflow: hidden;" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
перенеси в sprite.svg

2021-06-06 16:50 UTC, artem-bilodid commented on src/partials/contacts.html
> +    <use href="../src/icons/icon.svg#icon-btn"></use>
попробуй использовать icon-right из sprite.svg

2021-06-06 16:52 UTC, artem-bilodid commented on src/sass/components/_contacts.scss
> +       url('../images/contacts/point.png');
добавь дополнительную картинку и медиа запрос для ретина 2х

2021-06-06 16:56 UTC, artem-bilodid commented on src/partials/contacts.html
> +  <ul class="contacts__list list">
добавить contacts__container
ширину контейнера ограничить на точках перелома 480, 768, 1280 чтобы карточки не растягивались шире этих значений
на секции поставить розовый бекграунд , чтобы он тянулся по ширине на весь экран

2021-06-06 17:49 UTC, artem-bilodid requested changes

2021-06-06 17:49 UTC, artem-bilodid commented on src/partials/contacts.html
> +  <ul class="contacts__list list">
убрать .list, у тебя стили его и экстендят

2021-06-06 17:49 UTC, artem-bilodid commented on src/partials/contacts.html
> +      <div class="contacts__kategoriay-foodtruck">FOODTRUCK</div>
два слова food truck

2021-06-06 17:49 UTC, artem-bilodid commented on src/sass/components/_contacts.scss
> +  &__kategoriay-foodtruck {
_category

2021-06-06 17:49 UTC, artem-bilodid commented on src/sass/components/_contacts.scss
> +    color: var(text-color-prime);
--text-color-prime

2021-06-06 17:49 UTC, artem-bilodid commented on src/sass/components/_contacts.scss
> +  &__btn-Franchise {
добавить :hover стили
они нарисованы слева от макета
добавить cursor:pointer

2021-06-06 17:49 UTC, artem-bilodid commented on src/sass/main.scss
> +@import 'components/contacts';
перенести из компонентов в layout

2021-06-06 19:36 UTC, osipm commented on src/partials/contacts.html
> +  <ul class="contacts__list list">
list удалю коли зробимо загальні стилі

2021-06-07 10:34 UTC, artem-bilodid requested changes

2021-06-07 10:34 UTC, artem-bilodid commented on src/partials/contacts.html
> +<section class="contacts">
добавить id="contacts" для реализации навигации

2021-06-07 18:54 UTC, osipm commented on src/partials/contacts.html
> +  <ul class="contacts__list list">
виправив

2021-06-07 21:23 UTC, artem-bilodid approved these changes

2021-06-07 21:23 UTC, merged